#!/usr/bin/env bash
set -euo pipefail

set -x

readonly tmpDir=/tmp/update-github-deeep
mkdir -p $tmpDir
trap "rm -rf $tmpDir" EXIT

git clone bzr::http://code.alaiwan.org/bzr/games/deeep $tmpDir/repo
cd $tmpDir/repo
git remote add github https://github.com/Ace17/deeep.git
git push -f github
